### ISSUE TITLE
Node support 🙏

### ISSUE THREAD

**Issue by prescience-data** [wvbe/experimental-jsdoc-to-tsdoc-tool#5]
Just noticed the readme mentioning possible Node support if interest is there.

Just `+1`ing this, definitely would love to have this as part of precommit to fix autogenerated jsdoc blocks.

**Comment by wvbe** [comment]
Hey @prescience-data, thanks for submitting a ticket!

I did contemplate for a bit to write the script in NodeJS instead of Deno. Is that what you mean? Presumably you have NodeJS installed on your machine, but not Deno?

I may take some time to figure out Deno's ways of publishing for Node, and/or committing the built JS files to this repo, or otherwise. If you're looking for a quick solution you may be able to either install Deno on whichever machine runs your autofixes, or compile the script into a self-contained executable.

Again, thanks for your feedback ❤️

**Comment by prescience-data** [comment]
It's a bit of a complicated case involving a monorepo shared across many developers which may or may not have demo installed which makes it tricky to add to the build / linting process.

Fortunately the code is really clean so I've been able to make a local copy and start the conversion to Node for the use case.

Once it's stable I'll think about how to do a PR of some kind to make the Node version available if needed.

**Comment by wvbe** [comment]
Glad to hear you've had an alright experience finding your way in the code ;) Let me know if there's anything I can do to help -- and feel free to make other changes if you like.

I remember now that there's some Fonto-specific (my previous employer) stuff in here that I never took out. So not such clean code after all :D If you run into this, feel free to ignore/leave out that code.

**Comment by wvbe** [comment]
Hey @prescience-data, I figured out the `dnt` thing. This repository is now also published to npmjs.org, and [got a nice page there](https://www.npmjs.com/package/@wvbe/jsdoc-to-tsdoc)

If you find the time to try it I would be interested to hear if it worked for you without problems. If no problems I'll close this issue in a few days :)

All the best,
Wybe

**Comment by prescience-data** [comment]
Totally different topic but this would be cool to build as a [dprint](https://github.com/dprint) plugin as well. 
Same as above, working on this now and will push some conceptual code when I get it working.

`dprint` is a neat angle as it has IDE plugins so can re-rewrite on the fly rather than as a build step (which is how I'm using this plugin currently)

Recent HN thread: https://news.ycombinator.com/item?id=31160722
Plugin Docs: https://dprint.dev/plugin-dev/

**Comment by wvbe** [comment]
Makes total sense -- but can you create a new issue for that? I have some thoughts about it too that I'll share _there_

**Comment by wvbe** [comment]
**Closing issue! To wrap up with a conclusion;**

Compatibility with NodeJS was added by using Deno's `dnt` module, which transpiles Deno TS to JavaScript, `.d.ts` files and Deno-to-Node shims. It is now published as [@wvbe/jsdoc-to-tsdoc](https://www.npmjs.com/package/@wvbe/jsdoc-to-tsdoc).
